return PlaceObj('ModDef', {
	'title', "Fix Claustrophobia, Guilty, Sinful",
	'description', "Fix Claustrophobia, Guilty, Sinful, Proud and Righteous until devs do it.\n\nActually removes Claustrophobia debuff when changing map (like devs intended in the code).\n\nActually removes Guilty, Sinful, Proud and Righteous on next Calendar Day (likes devs intended in the code).\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/gvVuV4k/Images/fix-claustrophobia.png",
	'last_changes', "Fix bug with despawn (on change map)",
	'id', "gvVuV4k",
	'content_path', "Mod/gvVuV4k/",
	'author', "Audaki_ra",
	'version_major', 2,
	'version_minor', 2,
	'version', 36,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1690916509,
	'code_hash', 777029669703488161,
	'steam_id', "3013009157",
})