return PlaceObj('ModDef', {
	'title', "Stop AI Clairvoyance",
	'description', "Stops AI from being clairvoyant. They no longer magically update their scouting position towards your mercs with pin-point accuracy.\n\nInstead they will start a (half-random) search from the last known enemy position.\n\nThis might make the game easier for you, but also more enjoyable. Use this mod responsibly.\n\nSafe to add and remove at any time.",
	'image', "Mod/audaNoClairvoyant/Images/stop-ai-clairvoyance.png",
	'last_changes', "Add uninstall routine",
	'id', "audaNoClairvoyant",
	'content_path', "Mod/audaNoClairvoyant/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 2,
	'version', 48,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692093352,
	'code_hash', 3766839613154157462,
	'steam_id', "3020274812",
})