return PlaceObj('ModDef', {
	'title', "Free Camera Mode (Photo Mode)",
	'description', "Only enables Free Camera Mode and 3 other Camera related hotkeys.\n\n- SHIFT + C = Free Camera Mode\n- SHIFT + I = Hide overlay GUI\n- SHIFT + Y = Hide in-world GUI\n- ALT + SHIFT + H = Show Walls even when close-up\n\nThis mod changes NOTHING else.\nONLY the 3 listed hotkeys will be activated.\n\n# Tutorial Free Camera Mode\n\nIn Free Camera Mode the following is possible\n- Mouse = Freelook\n- WASD = move\n- CTRL + WASD = move fast\n- Q/E = move up/down\n- CTRL + Q/E = Move up/down fast\n- SHIFT + C = return to normal camera\n\nMod is safe to add and remove at any time.\n\nEnjoy :-)",
	'image', "Mod/oYqKgcN/Images/free-camera-mode.png",
	'last_changes', "Add SHIFT + Y",
	'id', "oYqKgcN",
	'content_path', "Mod/oYqKgcN/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 19,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1691513176,
	'code_hash', 3802855483591028997,
	'steam_id', "3016236168",
})