return PlaceObj('ModDef', {
	'title', "Fix Elbow Grease (Vickis Perk)",
	'description', "The Perk Elbow Grease (Vickis Perk) is sadly bugged in Vanilla. It doesn't work for every weapon, some never receive the damage/crit bonus.\n\nThis mod fixes the issue, so all fully modified weapons should properly receive the +7 damage and +15% crit bonus (the crit bonus is only visible while shooting)!\n\nMod is safe to add and remove at any time.\n\nEnjoy :-)",
	'image', "Mod/sA5kCaF/Images/fix-vicki-perk.png",
	'last_changes', "Fix Winchester (special case for slots that can be empty)",
	'id', "sA5kCaF",
	'content_path', "Mod/sA5kCaF/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 2,
	'version', 15,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1691517807,
	'code_hash', 2817532393554458066,
	'steam_id', "3016567532",
})