return PlaceObj('ModDef', {
	'title', "Option Sliders have Numbers!",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Option Sliders have Numbers![/h1]\n[h2]For Players[/h2]\nOption Sliders, especially Volume Sliders, should have Numbers.\n\nVolume and other Sliders now show Percent with this mod :-)\n\nThis is also a library for mods to show data and numbers on their Option Sliders.\n\n[h2]For Mod Authors[/h2]\nYou can set your own display type and postfix\n- valueDisplayType (supports showAll, percent, value and valueWithMax)\n- valueDisplayPostfix (shows a postfix like '$', 'XP', '%' or any other string)\n\ncan be setup like this:\n[code]\nif Zulib.setupModSlider then\n  Zulib.setupModSlider({\n    modId = CurrentModId,\n    optionId = 'myOptionId',\n    displayType = 'value',\n    displayPostfix = '%',\n  })\nend\n\n-- or\n\nif Zulib.setupModSlider then\n  Zulib.setupModSlider({\n    modId = CurrentModId,\n    optionId = 'myOptionId',\n    displayType = 'valueWithMax',\n  })\nend\n[/code]",
	'image', "Mod/0175sliders/Images/option-sliders-have-numbers.png",
	'last_changes', "Metadata",
	'dependencies', {},
	'id', "0175sliders",
	'author', "Audaki_ra",
	'version_major', 2,
	'version_minor', 1,
	'version', 13,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957690,
	'code_hash', -5445363486541209052,
	'steam_id', "3016669641",
	'TagGameSettings', true,
	'TagOther', true,
	'TagUI', true,
})