return PlaceObj('ModDef', {
	'title', "Trap is Mechanical or Explosive?",
	'description', "Shows more clearly if the trap is Mechanical or Explosive.\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/SsjbQho/Images/trap-is-mechanical.png",
	'last_changes', "Improve texts",
	'id', "SsjbQho",
	'content_path', "Mod/SsjbQho/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 61,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1690886467,
	'code_hash', 5008322865355443972,
	'steam_id', "3013111721",
})