return PlaceObj('ModDef', {
	'title', "Reduce Repetitive Voice",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Reduce Repetitive Voice[/h1]\nReduces Repetitive Voice Responses on Select and Move.\n\n=> You will have more silence on Select and Move mouse clicks.",
	'image', "Mod/audaReduceVoice/Images/reduce-repetitive-voice.png",
	'last_changes', "Metadata",
	'id', "audaReduceVoice",
	'author', "Audaki_ra",
	'version_major', 1,
	'version', 8,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957835,
	'code_hash', -4536538542425850243,
	'steam_id', "3022096173",
	'TagGameSettings', true,
	'TagOther', true,
})