return PlaceObj('ModDef', {
	'title', "Explain Morale Influences",
	'description', "Explain and show Morale Influences on Hover.\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/QQsMxHv/Images/explain-morale.png",
	'last_changes', 'Add support for "Remove all Dislikes (Morale)" mod',
	'id', "QQsMxHv",
	'content_path', "Mod/QQsMxHv/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 112,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1690887560,
	'code_hash', 4734361114630748233,
	'steam_id', "3012307920",
})