return PlaceObj('ModDef', {
	'title', "Explain Morale Influences",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Explain Morale Influences[/h1]\nExplain and show Morale Influences on Hover.\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/QQsMxHv/Images/explain-morale.png",
	'last_changes', "Metadata",
	'id', "QQsMxHv",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 116,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957656,
	'code_hash', 2389495802017366222,
	'steam_id', "3012307920",
	'TagOther', true,
	'TagUI', true,
})