return PlaceObj('ModDef', {
	'title', "Inventory Size Balance (Mild)",
	'description', "Improve Inventory Size Balancing by slightly increasing the scaling to grow every 3 1/2 STR and starts earlier.\n\nWith mod:\n 37 STR =  4 Slots\n 40 STR =  5 Slots\n 44 STR =  6 Slots\n 47 STR =  7 Slots\n 51 STR =  8 Slots\n 54 STR =  9 Slots\n 58 STR = 10 Slots\n 61 STR = 11 Slots\n 65 STR = 12 Slots\n 68 STR = 13 Slots\n 72 STR = 14 Slots\n 75 STR = 15 Slots\n 79 STR = 16 Slots\n 82 STR = 17 Slots\n 86 STR = 18 Slots\n 89 STR = 19 Slots\n 93 STR = 20 Slots\n 96 STR = 21 Slots\n100 STR = 22 Slots\n\nChange is done in a safe way by globally overriding the GetInventoryMaxSlots function, so it should work in all situations and UIs.\n\n(To remove mod first remove items from your backpacks that wouldn't fit otherwise)\n\nEnjoy :-)",
	'image', "Mod/abCMCNy/Images/inventory-size-balance.png",
	'last_changes', "Fix metadata",
	'id', "abCMCNy",
	'content_path', "Mod/abCMCNy/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version', 43,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1690458719,
	'code_hash', -8744826888428077174,
	'screenshot1', "Mod/abCMCNy/Images/inventory-size-ss1.png",
	'screenshot2', "Mod/abCMCNy/Images/inventory-size-ss2.png",
	'steam_id', "3009168318",
})