return PlaceObj('ModDef', {
	'title', "Audaki's Training Overhaul",
	'description', "Audaki's Training Overhaul is an overhaul mod for Training and Field Experience.\n\nWe felt in Vanilla JA3 Field Experience was too slow. And Agility improved too fast compared with others.\n\nThe reason was a really hard-capped statGainingPoint (we call them Train Points) system in Vanilla, where you only rarely got a single point allowance for a stat gain in Field Experience, and the stat that came first won.\n\nIn comparison to Sector Operation \"Train Merc\" this was extra bad. \"Train Merc\" was completely OP compared to Field Experience in Vanilla.\n\n=>\n\nThis mod changes all of this.\n\nYou get (many) more Train Points, this means Field Experience is finally worth it! And Agility can't steal so many points anymore. Since there is a cool down and you have enough points for other stats now.\n\nAdditionally Train Points are shared now between Field Experience and Sector Training Operation. That means you can no longer AFK train for months, you need to give your mercs some action.\n\nBut beware, if they only get action, your Train Points will cap at 30. After a lot of action you might get a notification that your merc should train so you can efficiently use your Train Points.\n\nIn the best case you will have a rhythm, do some action, do some training. Then your mercs will be happy and you have optimal training results.\n\n--\n\nAdditional Changes:\n\n- More statGainingPoints per Level\n- Can now stat roll more than once per map:\n- => TrapDisarmExplosives\n- => TrapDisarmMechanical\n- => ResourceDiscovery\n- => TrapDiscovery\n- ExplosiveMultiHit no longer has an extra fail chance\n- Most bonus rolls for stat rolls in Field Experience were reduced to give a little balance since you have enough points now\n- Field Experience rolls will get harder with higher stat now\n\nPS: Safe to add and remove at any time! (You might need to restart the game after disabling the mod)",
	'image', "Mod/audaTrainingOverhaul/Images/ttsj.png",
	'last_changes', "Moar Balancing",
	'id', "audaTrainingOverhaul",
	'content_path', "Mod/audaTrainingOverhaul/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 11,
	'version', 315,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
		"Code/OptionSliderDisplay.lua",
	},
	'has_options', true,
	'saved', 1691754037,
	'code_hash', 6064260459919229275,
	'steam_id', "3011437168",
})