return PlaceObj('ModDef', {
	'title', "Show XP and Level",
	'description', "While hovering over a merc, shows current Level, total XP and total XP required for next level.\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/SP7aFAU/Images/show-xp-and-level.png",
	'last_changes', "Add support for Custom Settings increase of max level",
	'id', "SP7aFAU",
	'content_path', "Mod/SP7aFAU/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 18,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1691333828,
	'code_hash', 9145145685053104408,
	'steam_id', "3011957956",
})