return PlaceObj('ModDef', {
	'title', "Trap is Mechanical or Explosive?",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Trap is Mechanical or Explosive?[/h1]\nShows more clearly if the trap is Mechanical or Explosive.\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/SsjbQho/Images/trap-is-mechanical.png",
	'last_changes', "Metadata",
	'id', "SsjbQho",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 63,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957774,
	'code_hash', -5907526377459952783,
	'steam_id', "3013111721",
	'TagOther', true,
	'TagUI', true,
})