return PlaceObj('ModDef', {
	'title', "Audaki’s Training Overhaul",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Audaki’s Training Overhaul[/h1]\nAfter developing TTSJ, the original training overhaul mod, I still wasn't fully satisfied. So I sat down and continued working and designing.\n\nThis mod is the result of 2 weeks of additional development time and over 100 hours of playtesting.\n\n[h2]Vision[/h2]\nImagine a play-through of JA3, where:\n[list]\n  [*] Activity (Combat, Quests) is always rewarded\n  [*] AFK Training is no longer a good strategy\n  [*] Activity in a sector will always benefit your mercs\n  [*] Overall, Sector Training Operation is Slower\n  [*] But Field Experience Gain is Faster and more even\n  [*] Static Cooldowns and once-per-map are Replaced with a Progress System\n[/list]\n\n[h3]In Field Experience[/h3]\n[list]\n  [*] Every skill use will be rewarded\n  [*] Example: Every defused mine/trap will count\n  [*] Skill uses either get a roll or grant Progress for the next roll\n  [*] With enough Progress your Merc is allowed to roll for a Stat Gain again\n  [*] Both Activity (Combat, Quests) and using the Skill will advance Progress\n[/list]\n\nThe most optimal strategy is now simply to let the merc you want to train fastest do the actions, without having to think anymore about cooldowns or once-a-map lockouts.\n\n[h3]Sector Operation Training[/h3]\nNow imagine in Sector Operation Training\n[list]\n  [*] Being inactive is no longer the best strategy\n  [*] Imagine, Training feels like a reward instead of cheating\n  [*] Earn Train Boosts via Activity (Combat, Quests)\n  [*] Without Train Boosts your Training will be extremely slow\n  [*] With Train Boosts your Training can be faster than Vanilla\n  [*] Spend Train Boosts in Sector Training Operation\n  [*] Sector Training Operation is now capped to 80 (configurable)\n  [*] Training now is a little slower when you simultaneously train more mercs\n  [*] First 5 Train Boosts get a slight boost in gain rate\n  [*] Therefore training more often in small intervals is worth it\n[/list]\n\nMod can be safely added and removed at any time. Although it is recommended to use this mod in a new play-through for balancing reasons.",
	'image', "Mod/audaAto/Images/audakis-training-overhaul.png",
	'last_changes', "Metadata",
	'dependencies', {},
	'id', "audaAto",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 13,
	'version', 437,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'has_options', true,
	'saved', 1692957615,
	'code_hash', -1385432814531819604,
	'steam_id', "3021099176",
	'TagBalancing', true,
	'TagGameSettings', true,
	'TagOther', true,
})