return PlaceObj('ModDef', {
	'title', "Scrap More!",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Scrap More![/h1]\nAllows you to scrap more items.\n\n[b]=> This makes the game easier![/b]\n\nChange is done in a new surgical way, only setting ScrapParts value, should even work with mods that change the same items as long as this mod comes last in load order.\n\nList of added Scrappables:\n- C4 = 3\n- ChippedSapphire = 2\n- Cookie (Biscuit) = 1\n- Combination_BalancingWeight = 3\n- Combination_CeramicPlates = 5\n- Combination_Detonator_Proximity = 5\n- Combination_Detonator_Remote = 5\n- Combination_Detonator_Time = 5\n- Combination_Sharpener = 3\n- Combination_WeavePadding = 5\n- ConcussiveGrenade = 5\n- FineSteelPipe = 5\n- FlareStick = 2\n- FragGrenade = 3\n- GlowStick = 2\n- HE_Grenade = 5\n- HerbalMedicine = 1\n- Knife = 2\n- Knife_Balanced = 2\n- Knife_Sharpened = 2\n- Microchip = 25\n- Molotov = 3\n- Money Bag = 2\n- OpticalLens = 5\n- PETN = 3\n- PipeBomb = 5\n- ProximityC4 = 8\n- ProximityPETN = 8\n- ProximityTNT = 8\n- RemoteC4 = 8\n- RemotePETN = 8\n- RemoteTNT = 8\n- ShapedCharge = 5\n- SmokeGrenade = 5\n- TearGasGrenade = 5\n- TimedC4 = 8\n- TimedPETN = 8\n- TimedTNT = 8\n- TNT = 3\n- ToxicGasGrenade = 5\n- TreasureFigurine = 3\n- TreasureGoldenDog = 3\n- TreasureIdol = 3\n- TreasureMask = 3\n- TreasureTablet = 3\n\nPS: For Dismantling Ammo and Explosives into Gunpowder please check out this mod:\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3010031059\n\nEnjoy :-)",
	'image', "Mod/etFjJsJ/Images/scrap-more.png",
	'last_changes', "Metadata",
	'id', "etFjJsJ",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 4,
	'version', 92,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957889,
	'code_hash', -3504466339230669192,
	'steam_id', "3009881596",
	'TagBalancing', true,
	'TagGameSettings', true,
})