return PlaceObj('ModDef', {
	'title', "Stop AI Clairvoyance",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Stop AI Clairvoyance[/h1]\nStops AI from being clairvoyant. They no longer magically update their scouting position towards your mercs with pin-point accuracy.\n\n[b]=> This makes the game easier![/b]\n\nInstead they will start a (half-random) search from the last known enemy position.\n\nThis might make the game easier for you, but also more enjoyable. Use this mod responsibly.\n\nSafe to add and remove at any time.",
	'image', "Mod/audaNoClairvoyant/Images/stop-ai-clairvoyance.png",
	'last_changes', "Make enemies a little harder",
	'id', "audaNoClairvoyant",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 3,
	'version', 52,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692958694,
	'code_hash', 8176129397566615257,
	'steam_id', "3020274812",
	'TagBalancing', true,
	'TagGameSettings', true,
})