return PlaceObj('ModDef', {
	'title', "Increase Scrap Parts",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Increase Scrap Parts[/h1]\nIf you don't have enough Parts, you can use this mod to increase the amount of Parts you get for Scrapping.\n\n[b]=> This makes the game easier![/b]\n\nCan set Scrap Amount between 110% (=10% more) and 400%.\n\n=> This will make your game easier, use according to your own judgement.\n\nPS: Safe to add and remove at any time (restart JA3.exe after disable).\n\nEnjoy :-)",
	'image', "Mod/siTbckx/Images/increase-scrap-parts.png",
	'last_changes', "Metadata",
	'id', "siTbckx",
	'author', "Audaki_ra",
	'version_major', 1,
	'version', 35,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'has_options', true,
	'saved', 1692957943,
	'code_hash', 5012744938481011233,
	'steam_id', "3013767865",
	'TagBalancing', true,
	'TagGameSettings', true,
})