return PlaceObj('ModDef', {
	'title', "Show Free Move AP",
	'description', "Internally Free Move actually has an AP number.\n\nThis mod shows the Free Move AP number.\n\nThat's it.\n\nSafe to add and remove at any time.\n\nEnjoy :-)",
	'image', "Mod/YfDhN7f/Images/show-free-move-ap.png",
	'last_changes', "Fix for localized games",
	'id', "YfDhN7f",
	'content_path', "Mod/YfDhN7f/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 75,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1690977538,
	'code_hash', 8293326263700583744,
	'steam_id', "3013755062",
})