return PlaceObj('ModDef', {
	'title', "Show Free Move AP",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Show Free Move AP[/h1]\nInternally Free Move actually has an AP number.\n\nThis mod shows the Free Move AP number.\n\nThat's it.\n\nSafe to add and remove at any time.\n\nEnjoy :-)",
	'image', "Mod/YfDhN7f/Images/show-free-move-ap.png",
	'last_changes', "Metadata",
	'id', "YfDhN7f",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 78,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957716,
	'code_hash', -2508267525278796565,
	'steam_id', "3013755062",
	'TagOther', true,
	'TagUI', true,
})