return PlaceObj('ModDef', {
	'title', "Volume Sliders have Numbers!",
	'description', "Volume Sliders have Feelings, erm, I mean, they have Numbers!\n\nOption Sliders also have Numbers!\n\nShow Volume and other Slider Percent with this mod :-)\n\nFor Mod Authors:\nYou can set your own display type and postfix\n- prop_meta.valueDisplayType (supports showAll, percent, value and valueWithMax)\n- prop_meta.valueDisplayPostfix (shows a postfix like '$', 'XP', '%' or any other string)",
	'image', "Mod/nDDKe5u/Images/volume-sliders-have-numbers.png",
	'last_changes', "Initial Release",
	'dependencies', {},
	'id', "nDDKe5u",
	'content_path', "Mod/nDDKe5u/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version', 14,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1691443268,
	'code_hash', -4494146644755190365,
	'steam_id', "3016669641",
})