return PlaceObj('ModDef', {
	'title', "Fix Learn to Like & Dislike",
	'description', "In Vanilla Learn to Like / Dislike is broken :(\n\nThe (dis-)like is not saved, and you do not get the morale effect. Instead they just start to (dis-)like again and again.\n\nAlso due to this you are missing out on specific banter that's supposed to play when the (dis-)like has already happened in the past.\n\nThis mod fixes the bug. Now \"Learn To\" works properly! They *keep* liking or disliking! And don't forget immediately after combat anymore..\n\nMod is safe to add and remove at any time.\n\nEnjoy :-)",
	'image', "Mod/AER5Xrw/Images/fix-learn-to-like-and-dislike.png",
	'last_changes', "Fix issue with table references",
	'id', "AER5Xrw",
	'content_path', "Mod/AER5Xrw/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 8,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1691286418,
	'code_hash', -5814102189335934986,
	'steam_id', "3015599875",
})