return PlaceObj('ModDef', {
	'title', "Show XP and Level",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Show XP and Level[/h1]\nWhile hovering over a merc, shows current Level, total XP and total XP required for next level.\n\nThat's it.\n\nSafe to add and remove at any time!\n\nEnjoy :-)",
	'image', "Mod/SP7aFAU/Images/show-xp-and-level.png",
	'last_changes', "Metadata",
	'id', "SP7aFAU",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 20,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957751,
	'code_hash', 9145145685053104408,
	'steam_id', "3011957956",
	'TagOther', true,
	'TagUI', true,
})