return PlaceObj('ModDef', {
	'title', "Colored Ammo in Weapon",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Colored Ammo in Weapon[/h1]\nColorize Ammo in Weapons (same color they have when hovering the ammo in Squad Supplies)\n\nSafe to add and remove at any time.\n\nPS: Mod does not work together with *MaxStacks Tweaks*\n\nEnjoy :-)",
	'image', "Mod/XadGsqw/Images/colored-ammo-in-weapons.png",
	'last_changes', "Metadata",
	'id', "XadGsqw",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 61,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957631,
	'code_hash', -2532308576942930811,
	'steam_id', "3014029872",
	'TagOther', true,
	'TagUI', true,
})