return PlaceObj('ModDef', {
	'title', "Show Tired / Rested Status",
	'description', "[h1]Compatibility[/h1]\n[h2]JA3 1.1.x ✓Compatible[/h2]\n\n[h1]Show Tired / Rested Status[/h1]\nShow Tired / Rested Status\n\n(Whenever your Health changes the remaining Tired Time will change, this is Vanilla Logic)\n\nMod is safe to add and remove at any time",
	'image', "Mod/audaShowTiredRest/Images/show-tired-rested-status.png",
	'last_changes', "Metadata",
	'id', "audaShowTiredRest",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 11,
	'version', 143,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692957731,
	'code_hash', -7268837119631729931,
	'steam_id', "3021381628",
	'TagOther', true,
	'TagUI', true,
})