return PlaceObj('ModDef', {
	'title', "Show Tired / Rested Status",
	'description', "Show Tired / Rested Status\n\n(Whenever your Health changes the remaining Tired Time will change, this is Vanilla Logic)\n\nMod is safe to add and remove at any time",
	'image', "Mod/audaShowTiredRest/Images/show-tired-rested-status.png",
	'last_changes', "Improve UX",
	'id', "audaShowTiredRest",
	'content_path', "Mod/audaShowTiredRest/",
	'author', "Audaki_ra",
	'version_major', 1,
	'version_minor', 1,
	'version', 121,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1692325935,
	'code_hash', -6950129944599731272,
	'steam_id', "3021381628",
})